language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"

cache:
  directories:
    - node_modules
    - typings

before_script:
  - ./node_modules/.bin/typings i
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success: ./coveralls.sh
